### PR TITLE
Added a link to Unifier Community Translations.

### PR DESCRIPTION
**Pull request by NullyIsHere**

### CODE REVIEW

**Comment by NullyIsHere** [comment]
@greeeen-dev

**Review by greeeen-dev — CHANGES_REQUESTED** [review]
Can we move the link down? Localization isn't one of the features Unifier is known for, so it's probably best to move this down, maybe to its own section or as a hyperlink under the Unifier subheading.

**Comment by NullyIsHere** [comment]
Better now?

**Review by greeeen-dev — APPROVED** [review]
Not really happy with the position still, but I'll merge it anyways and figure something out

**Pull request merged**
